Tsavo lions have barely any mane.

A tiger's territory and hunting range is drastically reduced when she has cubs.

Cheetahs eat quickly, before other predators can chase them off and steal their kill.

Clouded leopards have the largest canines relative to body size, among all wild cats.

Snow leopards can't roar.

<!--
**jackton-jam/jackton-jam** is a ✨ _special_ ✨ repository because its `README.md` (this file) appears on your GitHub profile.

Here are some ideas to get you started:

- 🔭 I’m currently working on ...
- 🌱 I’m currently learning ...
- 👯 I’m looking to collaborate on ...
- 🤔 I’m looking for help with ...
- 💬 Ask me about ...
- 📫 How to reach me: ...
- 😄 Pronouns: ...
- ⚡ Fun fact: ...
-->
